name: Deploy OpenAPI docs

on:
  push:
    branches: [devel]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          pipx install poetry

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
          # cache: 'poetry'

      - name: Run poetry install
        run: |
          poetry env use '3.10'
          poetry install
        
      - name: Build openapi.json
        run: |
          mkdir gh_pages
          poetry run python -c "from langqc_state.main import app; import json; output = open('gh-pages/openapi.json', 'w'); json.dump(app.openapi(), output); output.close()"

      - name: Deploy github pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: gh-pages
